version: '3.4'

services:
  mssql:
    hostname: ${SQL_HOST:-mssql}
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      network:
        aliases:
          - ${SQL_HOST:-mssql}
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=${SQL_PASSWORD:-hNxX9Qz2}

networks:
  network: