version: '3.4'

services:
  dogger-setup:
    build: 
        context: .
        dockerfile: ./Dogger.Setup/Dockerfile
    image: docker.pkg.github.com/dogger/app.dogger.io/dogger-setup:${Dogfeed__Tag:-latest}
    networks:
    - network
    volumes:
    - "./:/pwd/"
    environment:
    - Dogfeed__DockerRegistry__HostName=${Dogfeed__DockerRegistry__HostName:-docker.pkg.github.com}
    - Dogfeed__DockerRegistry__Username=${Dogfeed__DockerRegistry__Username}
    - Dogfeed__DockerRegistry__Password=${Dogfeed__DockerRegistry__Password}
    env_file:
     - ./env/dogger.env

networks:
  network: