version: '3.4'

services:
  dogger-tests:
    image: ${DOCKER_REGISTRY-}dogger-tests
    networks:
    - network
    build:
      context: .
      dockerfile: src/Dogger.Tests/Dockerfile
    volumes:
      - "./TestResults/Dogger:/src/Dogger.Tests/TestResults/Dogger"
    environment:
    - DOTNET_RUNNING_IN_TEST=true

  dogger-setup-tests:
    image: ${DOCKER_REGISTRY-}dogger-setup-tests
    networks:
    - network
    build:
      context: .
      dockerfile: src/Dogger.Setup.Tests/Dockerfile
    volumes:
      - "./TestResults/Dogger.Setup:/src/Dogger.Setup.Tests/TestResults/Dogger.Setup"
    environment:
    - DOTNET_RUNNING_IN_TEST=true

  mssql:
    tmpfs: /var/lib/mssql:rw,exec,suid,dev
    logging:
      driver: none

networks:
  network: