/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangePlanRequest
 */
export interface ChangePlanRequest {
    /**
     * 
     * @type {number}
     * @memberof ChangePlanRequest
     */
    poolSize?: number;
    /**
     * 
     * @type {string}
     * @memberof ChangePlanRequest
     */
    planId?: string | null;
}

export function ChangePlanRequestFromJSON(json: any): ChangePlanRequest {
    return ChangePlanRequestFromJSONTyped(json, false);
}

export function ChangePlanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePlanRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'poolSize': !exists(json, 'poolSize') ? undefined : json['poolSize'],
        'planId': !exists(json, 'planId') ? undefined : json['planId'],
    };
}

export function ChangePlanRequestToJSON(value?: ChangePlanRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'poolSize': value.poolSize,
        'planId': value.planId,
    };
}


