/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InstanceResponse,
    InstanceResponseFromJSON,
    InstanceResponseFromJSONTyped,
    InstanceResponseToJSON,
} from './';

/**
 * 
 * @export
 * @interface ClusterResponse
 */
export interface ClusterResponse {
    /**
     * 
     * @type {string}
     * @memberof ClusterResponse
     */
    id?: string;
    /**
     * 
     * @type {Array<InstanceResponse>}
     * @memberof ClusterResponse
     */
    instances?: Array<InstanceResponse> | null;
}

export function ClusterResponseFromJSON(json: any): ClusterResponse {
    return ClusterResponseFromJSONTyped(json, false);
}

export function ClusterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'instances': !exists(json, 'instances') ? undefined : (json['instances'] === null ? null : (json['instances'] as Array<any>).map(InstanceResponseFromJSON)),
    };
}

export function ClusterResponseToJSON(value?: ClusterResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'instances': value.instances === undefined ? undefined : (value.instances === null ? null : (value.instances as Array<any>).map(InstanceResponseToJSON)),
    };
}


