/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConversationMode,
    ConversationModeFromJSON,
    ConversationModeFromJSONTyped,
    ConversationModeToJSON,
} from './';

/**
 * 
 * @export
 * @interface ConfigurationFileOverride
 */
export interface ConfigurationFileOverride {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ConfigurationFileOverride
     */
    buildArguments?: { [key: string]: string; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigurationFileOverride
     */
    dockerComposeYmlFilePaths?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigurationFileOverride
     */
    additionalPaths?: Array<string> | null;
    /**
     * 
     * @type {ConversationMode}
     * @memberof ConfigurationFileOverride
     */
    conversationMode?: ConversationMode;
}

export function ConfigurationFileOverrideFromJSON(json: any): ConfigurationFileOverride {
    return ConfigurationFileOverrideFromJSONTyped(json, false);
}

export function ConfigurationFileOverrideFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigurationFileOverride {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildArguments': !exists(json, 'buildArguments') ? undefined : json['buildArguments'],
        'dockerComposeYmlFilePaths': !exists(json, 'dockerComposeYmlFilePaths') ? undefined : json['dockerComposeYmlFilePaths'],
        'additionalPaths': !exists(json, 'additionalPaths') ? undefined : json['additionalPaths'],
        'conversationMode': !exists(json, 'conversationMode') ? undefined : ConversationModeFromJSON(json['conversationMode']),
    };
}

export function ConfigurationFileOverrideToJSON(value?: ConfigurationFileOverride | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buildArguments': value.buildArguments,
        'dockerComposeYmlFilePaths': value.dockerComposeYmlFilePaths,
        'additionalPaths': value.additionalPaths,
        'conversationMode': ConversationModeToJSON(value.conversationMode),
    };
}


