/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExposedPort,
    ExposedPortFromJSON,
    ExposedPortFromJSONTyped,
    ExposedPortToJSON,
} from './';

/**
 * 
 * @export
 * @interface ConnectionDetailsResponse
 */
export interface ConnectionDetailsResponse {
    /**
     * 
     * @type {string}
     * @memberof ConnectionDetailsResponse
     */
    readonly ipAddress?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConnectionDetailsResponse
     */
    readonly hostName?: string | null;
    /**
     * 
     * @type {Array<ExposedPort>}
     * @memberof ConnectionDetailsResponse
     */
    readonly ports?: Array<ExposedPort> | null;
}

export function ConnectionDetailsResponseFromJSON(json: any): ConnectionDetailsResponse {
    return ConnectionDetailsResponseFromJSONTyped(json, false);
}

export function ConnectionDetailsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionDetailsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ipAddress': !exists(json, 'ipAddress') ? undefined : json['ipAddress'],
        'hostName': !exists(json, 'hostName') ? undefined : json['hostName'],
        'ports': !exists(json, 'ports') ? undefined : (json['ports'] === null ? null : (json['ports'] as Array<any>).map(ExposedPortFromJSON)),
    };
}

export function ConnectionDetailsResponseToJSON(value?: ConnectionDetailsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


