/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ConversationMode {
    SingleComment = 'singleComment',
    MultipleComments = 'multipleComments'
}

export function ConversationModeFromJSON(json: any): ConversationMode {
    return ConversationModeFromJSONTyped(json, false);
}

export function ConversationModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationMode {
    return json as ConversationMode;
}

export function ConversationModeToJSON(value?: ConversationMode | null): any {
    return value as any;
}

