/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeployToClusterResponse
 */
export interface DeployToClusterResponse {
    /**
     * 
     * @type {string}
     * @memberof DeployToClusterResponse
     */
    jobId?: string | null;
}

export function DeployToClusterResponseFromJSON(json: any): DeployToClusterResponse {
    return DeployToClusterResponseFromJSONTyped(json, false);
}

export function DeployToClusterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeployToClusterResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jobId': !exists(json, 'jobId') ? undefined : json['jobId'],
    };
}

export function DeployToClusterResponseToJSON(value?: DeployToClusterResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jobId': value.jobId,
    };
}


