/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileRequest
 */
export interface FileRequest {
    /**
     * 
     * @type {string}
     * @memberof FileRequest
     */
    path?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileRequest
     */
    contents?: string | null;
}

export function FileRequestFromJSON(json: any): FileRequest {
    return FileRequestFromJSONTyped(json, false);
}

export function FileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'path': !exists(json, 'path') ? undefined : json['path'],
        'contents': !exists(json, 'contents') ? undefined : json['contents'],
    };
}

export function FileRequestToJSON(value?: FileRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'path': value.path,
        'contents': value.contents,
    };
}


