/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserPayload,
    UserPayloadFromJSON,
    UserPayloadFromJSONTyped,
    UserPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface HeadPayload
 */
export interface HeadPayload {
    /**
     * 
     * @type {string}
     * @memberof HeadPayload
     */
    ref?: string | null;
    /**
     * 
     * @type {string}
     * @memberof HeadPayload
     */
    sha?: string | null;
    /**
     * 
     * @type {UserPayload}
     * @memberof HeadPayload
     */
    user?: UserPayload;
}

export function HeadPayloadFromJSON(json: any): HeadPayload {
    return HeadPayloadFromJSONTyped(json, false);
}

export function HeadPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): HeadPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ref': !exists(json, 'ref') ? undefined : json['ref'],
        'sha': !exists(json, 'sha') ? undefined : json['sha'],
        'user': !exists(json, 'user') ? undefined : UserPayloadFromJSON(json['user']),
    };
}

export function HeadPayloadToJSON(value?: HeadPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ref': value.ref,
        'sha': value.sha,
        'user': UserPayloadToJSON(value.user),
    };
}


