/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstallationPayload
 */
export interface InstallationPayload {
    /**
     * 
     * @type {number}
     * @memberof InstallationPayload
     */
    id?: number;
}

export function InstallationPayloadFromJSON(json: any): InstallationPayload {
    return InstallationPayloadFromJSONTyped(json, false);
}

export function InstallationPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstallationPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function InstallationPayloadToJSON(value?: InstallationPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


