/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstanceResponse
 */
export interface InstanceResponse {
    /**
     * 
     * @type {string}
     * @memberof InstanceResponse
     */
    id?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InstanceResponse
     */
    cpuCount?: number;
    /**
     * 
     * @type {number}
     * @memberof InstanceResponse
     */
    ramSizeInMegabytes?: number;
    /**
     * 
     * @type {number}
     * @memberof InstanceResponse
     */
    transferPerMonthInGigabytes?: number;
    /**
     * 
     * @type {number}
     * @memberof InstanceResponse
     */
    diskSizeInGigabytes?: number;
    /**
     * 
     * @type {string}
     * @memberof InstanceResponse
     */
    publicIpAddressV4?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InstanceResponse
     */
    publicIpAddressV6?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InstanceResponse
     */
    privateIpAddress?: string | null;
}

export function InstanceResponseFromJSON(json: any): InstanceResponse {
    return InstanceResponseFromJSONTyped(json, false);
}

export function InstanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'cpuCount': !exists(json, 'cpuCount') ? undefined : json['cpuCount'],
        'ramSizeInMegabytes': !exists(json, 'ramSizeInMegabytes') ? undefined : json['ramSizeInMegabytes'],
        'transferPerMonthInGigabytes': !exists(json, 'transferPerMonthInGigabytes') ? undefined : json['transferPerMonthInGigabytes'],
        'diskSizeInGigabytes': !exists(json, 'diskSizeInGigabytes') ? undefined : json['diskSizeInGigabytes'],
        'publicIpAddressV4': !exists(json, 'publicIpAddressV4') ? undefined : json['publicIpAddressV4'],
        'publicIpAddressV6': !exists(json, 'publicIpAddressV6') ? undefined : json['publicIpAddressV6'],
        'privateIpAddress': !exists(json, 'privateIpAddress') ? undefined : json['privateIpAddress'],
    };
}

export function InstanceResponseToJSON(value?: InstanceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'cpuCount': value.cpuCount,
        'ramSizeInMegabytes': value.ramSizeInMegabytes,
        'transferPerMonthInGigabytes': value.transferPerMonthInGigabytes,
        'diskSizeInGigabytes': value.diskSizeInGigabytes,
        'publicIpAddressV4': value.publicIpAddressV4,
        'publicIpAddressV6': value.publicIpAddressV6,
        'privateIpAddress': value.privateIpAddress,
    };
}


