/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IssuePayload
 */
export interface IssuePayload {
    /**
     * 
     * @type {number}
     * @memberof IssuePayload
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof IssuePayload
     */
    state?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof IssuePayload
     */
    locked?: boolean;
    /**
     * 
     * @type {number}
     * @memberof IssuePayload
     */
    number?: number;
    /**
     * 
     * @type {object}
     * @memberof IssuePayload
     */
    pullRequest?: object;
}

export function IssuePayloadFromJSON(json: any): IssuePayload {
    return IssuePayloadFromJSONTyped(json, false);
}

export function IssuePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuePayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'locked': !exists(json, 'locked') ? undefined : json['locked'],
        'number': !exists(json, 'number') ? undefined : json['number'],
        'pullRequest': !exists(json, 'pull_request') ? undefined : json['pull_request'],
    };
}

export function IssuePayloadToJSON(value?: IssuePayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'state': value.state,
        'locked': value.locked,
        'number': value.number,
        'pull_request': value.pullRequest,
    };
}


