/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentMethodResponse
 */
export interface PaymentMethodResponse {
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodResponse
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodResponse
     */
    brand?: string | null;
}

export function PaymentMethodResponseFromJSON(json: any): PaymentMethodResponse {
    return PaymentMethodResponseFromJSONTyped(json, false);
}

export function PaymentMethodResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethodResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'brand': !exists(json, 'brand') ? undefined : json['brand'],
    };
}

export function PaymentMethodResponseToJSON(value?: PaymentMethodResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'brand': value.brand,
    };
}


