/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    JobStatusResponse,
    JobStatusResponseFromJSON,
    JobStatusResponseFromJSONTyped,
    JobStatusResponseToJSON,
} from './';

/**
 * 
 * @export
 * @interface PlanProvisionResponse
 */
export interface PlanProvisionResponse {
    /**
     * 
     * @type {JobStatusResponse}
     * @memberof PlanProvisionResponse
     */
    status?: JobStatusResponse;
    /**
     * 
     * @type {string}
     * @memberof PlanProvisionResponse
     */
    jobId?: string | null;
}

export function PlanProvisionResponseFromJSON(json: any): PlanProvisionResponse {
    return PlanProvisionResponseFromJSONTyped(json, false);
}

export function PlanProvisionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanProvisionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : JobStatusResponseFromJSON(json['status']),
        'jobId': !exists(json, 'jobId') ? undefined : json['jobId'],
    };
}

export function PlanProvisionResponseToJSON(value?: PlanProvisionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': JobStatusResponseToJSON(value.status),
        'jobId': value.jobId,
    };
}


