/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConfigurationFileOverride,
    ConfigurationFileOverrideFromJSON,
    ConfigurationFileOverrideFromJSONTyped,
    ConfigurationFileOverrideToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProvisionRequest
 */
export interface ProvisionRequest {
    /**
     * 
     * @type {string}
     * @memberof ProvisionRequest
     */
    repositoryHandle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProvisionRequest
     */
    pullRequestHandle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProvisionRequest
     */
    commitReference?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProvisionRequest
     */
    apiKey?: string | null;
    /**
     * 
     * @type {ConfigurationFileOverride}
     * @memberof ProvisionRequest
     */
    _configuration?: ConfigurationFileOverride;
}

export function ProvisionRequestFromJSON(json: any): ProvisionRequest {
    return ProvisionRequestFromJSONTyped(json, false);
}

export function ProvisionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProvisionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'repositoryHandle': !exists(json, 'repositoryHandle') ? undefined : json['repositoryHandle'],
        'pullRequestHandle': !exists(json, 'pullRequestHandle') ? undefined : json['pullRequestHandle'],
        'commitReference': !exists(json, 'commitReference') ? undefined : json['commitReference'],
        'apiKey': !exists(json, 'apiKey') ? undefined : json['apiKey'],
        '_configuration': !exists(json, 'configuration') ? undefined : ConfigurationFileOverrideFromJSON(json['configuration']),
    };
}

export function ProvisionRequestToJSON(value?: ProvisionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'repositoryHandle': value.repositoryHandle,
        'pullRequestHandle': value.pullRequestHandle,
        'commitReference': value.commitReference,
        'apiKey': value.apiKey,
        'configuration': ConfigurationFileOverrideToJSON(value._configuration),
    };
}


