/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    HeadPayload,
    HeadPayloadFromJSON,
    HeadPayloadFromJSONTyped,
    HeadPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface PullRequestPayload
 */
export interface PullRequestPayload {
    /**
     * 
     * @type {number}
     * @memberof PullRequestPayload
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof PullRequestPayload
     */
    number?: number;
    /**
     * 
     * @type {string}
     * @memberof PullRequestPayload
     */
    state?: string | null;
    /**
     * 
     * @type {HeadPayload}
     * @memberof PullRequestPayload
     */
    head?: HeadPayload;
    /**
     * 
     * @type {boolean}
     * @memberof PullRequestPayload
     */
    draft?: boolean;
}

export function PullRequestPayloadFromJSON(json: any): PullRequestPayload {
    return PullRequestPayloadFromJSONTyped(json, false);
}

export function PullRequestPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PullRequestPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'number': !exists(json, 'number') ? undefined : json['number'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'head': !exists(json, 'head') ? undefined : HeadPayloadFromJSON(json['head']),
        'draft': !exists(json, 'draft') ? undefined : json['draft'],
    };
}

export function PullRequestPayloadToJSON(value?: PullRequestPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'number': value.number,
        'state': value.state,
        'head': HeadPayloadToJSON(value.head),
        'draft': value.draft,
    };
}


