/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SettingsResponse
 */
export interface SettingsResponse {
    /**
     * 
     * @type {string}
     * @memberof SettingsResponse
     */
    planId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SettingsResponse
     */
    apiKey?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    poolSize?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    isInstalled?: boolean;
}

export function SettingsResponseFromJSON(json: any): SettingsResponse {
    return SettingsResponseFromJSONTyped(json, false);
}

export function SettingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'planId': !exists(json, 'planId') ? undefined : json['planId'],
        'apiKey': !exists(json, 'apiKey') ? undefined : json['apiKey'],
        'poolSize': !exists(json, 'poolSize') ? undefined : json['poolSize'],
        'isInstalled': !exists(json, 'isInstalled') ? undefined : json['isInstalled'],
    };
}

export function SettingsResponseToJSON(value?: SettingsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'planId': value.planId,
        'apiKey': value.apiKey,
        'poolSize': value.poolSize,
        'isInstalled': value.isInstalled,
    };
}


