/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum SocketProtocol {
    Tcp = 'tcp',
    Udp = 'udp'
}

export function SocketProtocolFromJSON(json: any): SocketProtocol {
    return SocketProtocolFromJSONTyped(json, false);
}

export function SocketProtocolFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocketProtocol {
    return json as SocketProtocol;
}

export function SocketProtocolToJSON(value?: SocketProtocol | null): any {
    return value as any;
}

