version: '3.4'

services:
  dogger:
    image: docker.pkg.github.com/dogger/app.dogger.io/dogger:${DOGGER_TAG:-latest}
    restart: always
    networks:
    - network
    ports:
    - "80:80"
    - "443:443"

networks:
  network: