version: '3.4'

services:
  dogger-setup:
    build: 
        context: .
        dockerfile: ./Dogger.Setup/Dockerfile
    image: docker.pkg.github.com/dogger/app.dogger.io/dogger-setup:${DOGGER_TAG:-latest}
    networks:
    - network
    volumes:
    - "./pwd/:/pwd/"
    env_file:
     - /pwd/env/dogger.env

networks:
  network: