version: '3.4'

services:
  dogger:
    env_file:
     - ./env/dogger.env
    depends_on:
     - "elasticsearch"
     - "kibana"

  elasticsearch:
    image: xtermi2/elasticsearch-searchguard:7.6.1
    container_name: elasticsearch
    networks:
    - network
    env_file:
     - ./env/elasticsearch.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elk/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elk/certs:/usr/share/elasticsearch/config/certificates
    restart: always
    healthcheck:
      test: curl -X GET -f -k -u 'elastic:elastic' https://localhost:9200 || exit 1
      interval: 60s
      timeout: 5s
      retries: 60

  kibana:
    image: xtermi2/kibana-searchguard:7.6.1
    container_name: kibana
    networks:
    - network
    env_file:
     - ./env/kibana.env
    ports:
      - "5601:5601"
    restart: always
    healthcheck:
      test: curl -X GET -f http://localhost:5601/status || exit 1
      interval: 60s
      timeout: 5s
      retries: 60
    depends_on:
      - "elasticsearch"