version: '3.4'

services:
  dogger:
    depends_on:
     - "elasticsearch"
     - "kibana"

  elasticsearch:
    image: xtermi2/elasticsearch-searchguard:7.6.1
    container_name: elasticsearch
    networks:
    - network
    environment:
    - node.name=elasticsearch
    - discovery.type=single-node
    - ES_JAVA_OPTS=-Xms256m -Xmx256m
    - ROOT_CA=root-ca.pem
    - ADMIN_PEM=admin.pem
    - ADMIN_KEY=admin.key
    - ADMIN_KEY_PASS=${ELASTICSEARCH_ADMIN_KEY_PASSWORD}
    - ELASTIC_PWD=elastic
    - KIBANA_PWD={ELASTICSEARCH_INSTANCE_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./certs:/usr/share/elasticsearch/config/certificates
    restart: always
    healthcheck:
      test: curl -X GET -f -k -u 'elastic:elastic' https://localhost:9200 || exit 1
      interval: 60s
      timeout: 5s
      retries: 60

  kibana:
    image: xtermi2/kibana-searchguard:7.6.1
    container_name: kibana
    networks:
    - network
    environment:
    - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
    - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
    - ELASTICSEARCH_USERNAME=kibana
    - ELASTICSEARCH_PASSWORD={ELASTICSEARCH_INSTANCE_PASSWORD}
    ports:
      - "5601:5601"
    restart: always
    healthcheck:
      test: curl -X GET -f http://localhost:5601/status || exit 1
      interval: 60s
      timeout: 5s
      retries: 60
    depends_on:
      - "elasticsearch"