version: '3.4'

services:
  dogger:
    image: docker.pkg.github.com/dogger/app.dogger.io/dogger:${DOGGER_TAG:-latest}
    restart: always
    networks:
    - network
    ports:
    - "80:80"
    - "443:443"
    environment:
    - Aws__AccessKeyId=${AWS_ACCESS_KEY_ID}
    - Aws__SecretAccessKey=${AWS_SECRET_ACCESS_KEY}
    - Aws__LightsailPrivateKeyPem=${AWS_LIGHTSAIL_PRIVATE_KEY_PEM:-}
    - Slack__IncomingUrl=${SLACK_INCOMING_WEBHOOK_URL:-}
    - Encryption__Pepper=${ENCRYPTION_PEPPER:-e32ae512-deb8-44b8-82d1-8f3af58fec28}
    - Sql__ConnectionString=Server=${SQL_HOST:-mssql},${SQL_PORT:-1433};Database=${SQL_DATABASE:-master};User Id=${SQL_USERNAME:-SA};Password=${SQL_PASSWORD:-hNxX9Qz2}
    - Stripe__SecretKey=${STRIPE_SECRET_KEY:-}
    - Stripe__PublishableKey=${STRIPE_SECRET_KEY:-}
    - ASPNETCORE_ENVIRONMENT=Production

networks:
  network: